name: Backup Repositories

on:
  schedule:
    - cron: '0 */2 * * *'  
  workflow_dispatch:
  
jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Backup Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          
      - name: Clone and Move Repositories
        run: |
          clone_and_move() {
            local repo_url=$1
            local temp_dir=$2
            local target_dir=$3
            git clone --depth=1 $repo_url $temp_dir
            rm -rf "$target_dir"
            mkdir -p "$target_dir"
            mv $temp_dir/* "$target_dir/"
            rm -rf $temp_dir
          }

          clone_and_move "https://github.com/CuiCuiSha233/wechat_for_handsome -b master" "CuiCuiSha233_wechat_for_handsome" "wechat_for_handsome(CuiCuiSha233)"
      - name: Update timestamp
        run: echo "Backup run at $(date)" > backup-timestamp.txt
        
      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected, adding timestamp file."
            echo "Backup run at $(date)" > backup-timestamp.txt
            git add backup-timestamp.txt
            git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
          else
            git commit -m "Automated backup $(date +'%Y-%m-%d %H:%M:%S')"
          fi
          git remote set-url origin https://x-access-token:${PAT}@github.com/smjcxf/pz.git
          git push origin main    
